// Traditional Brazilian rhythmic pattern library (fragment-ID sequences)
  const traditionalPatterns = [
    {"id": "sincope-caratteristica", "name": "Síncope Característica", "style": "Brazilian rhythm grammar", "fragments": ["A1", "B1", "A1", "B1"], "description": "Characteristic syncopation pattern."},
    {"id": "maxixe-01", "name": "Maxixe 1", "style": "Maxixe", "fragments": ["A1", "B2", "A1", "B2"], "description": "Maxixe pattern."},
    {"id": "maxixe-02", "name": "Maxixe 2", "style": "Maxixe", "fragments": ["A2", "B8", "A2", "B8"], "description": "Alternative maxixe pattern."},
    {"id": "maxixe-var1", "name": "Maxixe var. 1", "style": "Maxixe", "fragments": ["A2", "B8", "A2", "B6"], "description": "Maxixe variation."},
    {"id": "partido-alto-revision", "name": "Partido Alto — to revise", "style": "Partido Alto", "fragments": ["A5", "B1", "B1", "A2"], "description": "Marked by user as needing correction."},
    {"id": "partido-alto-var1", "name": "Partido Alto var. 1", "style": "Partido Alto", "fragments": ["B5", "B1", "B3", "A2"], "description": "Partido alto variation."},
    {"id": "partido-alto-var2", "name": "Partido Alto var. 2", "style": "Partido Alto", "fragments": ["A5", "B1", "B3", "A2"], "description": "Partido alto variation."},
    {"id": "partido-alto-var3", "name": "Partido Alto var. 3", "style": "Partido Alto", "fragments": ["A5", "B1", "B2", "A2"], "description": "Partido alto variation."},
    {"id": "partido-alto-var4", "name": "Partido Alto var. 4", "style": "Partido Alto", "fragments": ["B5", "B2", "B2", "A2"], "description": "Partido alto variation."},
    {"id": "telecoteco-01", "name": "Telecoteco 1", "style": "Samba", "fragments": ["A2", "B6", "B1", "A1"], "description": "Telecoteco pattern."},
    {"id": "telecoteco-02", "name": "Telecoteco 2", "style": "Samba", "fragments": ["B1", "A1", "A2", "B6"], "description": "Telecoteco variation."},
    {"id": "agogo-01", "name": "Agogô 1", "style": "Agogô", "fragments": ["A2", "B1", "B1", "A2"], "description": "Agogô pattern."},
    {"id": "agogo-02", "name": "Agogô 2", "style": "Agogô", "fragments": ["A2", "B6", "B3", "A2"], "description": "Agogô variation."},
    {"id": "velha-guarda-estacio", "name": "Velha Guarda Estácio", "style": "Samba", "fragments": ["A2", "B8", "B1", "A3"], "description": "Velha Guarda / Estácio samba pattern."},
    {"id": "samba-01", "name": "Samba", "style": "Samba", "fragments": ["A2", "B8", "B1", "A2"], "description": "Samba pattern."},
    {"id": "samba-classico", "name": "Samba clássico", "style": "Samba", "fragments": ["A2", "B6", "B3", "A2"], "description": "Classic samba pattern. Same sequence as Agogô 2, kept as separate stylistic label."},
    {"id": "tango-brasileiro", "name": "Tango Brasileiro", "style": "Tango Brasileiro", "fragments": ["A3", "A3", "A3", "A1"], "description": "Tango brasileiro pattern."},
    {"id": "bossa-01", "name": "Bossa 1", "style": "Bossa Nova", "fragments": ["B1", "A5", "B1", "A5"], "description": "Bossa pattern."},
    {"id": "bossa-02", "name": "Bossa 2", "style": "Bossa Nova", "fragments": ["B1", "A2", "A2", "B8"], "description": "Alternative bossa pattern."},
    {"id": "baiao-01", "name": "Baião 1", "style": "Baião", "fragments": ["A3", "B8", "A3", "B8"], "description": "Baião pattern."},
    {"id": "baiao-02", "name": "Baião 2", "style": "Baião", "fragments": ["A3", "B5", "A3", "B5"], "description": "Baião pattern. Same sequence as Frag. Melodico 4 / Jura, kept as separate stylistic label."},
    {"id": "baiao-03", "name": "Baião 3", "style": "Baião", "fragments": ["A3", "B8", "A3", "B5"], "description": "Baião variation."},
    {"id": "baiao-04", "name": "Baião 4", "style": "Baião", "fragments": ["A3", "B8", "A3", "B9"], "description": "Baião variation."},
    {"id": "baiao-05", "name": "Baião 5", "style": "Baião", "fragments": ["B6", "A1", "B6", "A1"], "description": "Baião variation."},
    {"id": "ijexa-axe-01", "name": "Ijexá/Axé 1", "style": "Ijexá/Axé", "fragments": ["A1", "B1", "B9", "B1"], "description": "Ijexá/Axé pattern."},
    {"id": "ijexa-axe-02", "name": "Ijexá/Axé 2", "style": "Ijexá/Axé", "fragments": ["A1", "B4", "B8", "B1"], "description": "Ijexá/Axé pattern."},
    {"id": "ijexa-01", "name": "Ijexá", "style": "Ijexá", "fragments": ["B1", "B1", "A1", "B6"], "description": "Ijexá pattern."},
    {"id": "maracatu-gongue", "name": "Maracatu — gonguê", "style": "Maracatu", "fragments": ["B1", "B1", "A1", "B1"], "description": "Maracatu gonguê pattern."},
    {"id": "maracatu-congas-01", "name": "Maracatu — congas 1", "style": "Maracatu", "fragments": ["B1", "B4", "A1", "B4"], "description": "Maracatu congas pattern."},
    {"id": "maracatu-congas-02", "name": "Maracatu — congas 2", "style": "Maracatu", "fragments": ["B2", "B4", "A1", "B4"], "description": "Maracatu congas variation."},
    {"id": "baque-luanda-gongue", "name": "Baque de Luanda — gonguê", "style": "Maracatu / Baque de Luanda", "fragments": ["A3", "B1", "A1", "B1"], "description": "Baque de Luanda gonguê pattern."},
    {"id": "frag-melodico-01-barracao", "name": "Frag. Melódico 1 — Barracão", "style": "Melodic fragment", "fragments": ["B10", "B1", "A3", "A2"], "description": "Melodic fragment from Barracão."},
    {"id": "frag-melodico-02-carcara", "name": "Frag. Melódico 2 — Carcará", "style": "Melodic fragment", "fragments": ["A2", "A1", "A1", "B1"], "description": "Melodic fragment from Carcará."},
    {"id": "frag-melodico-03-one-note-samba", "name": "Frag. Melódico 3 — One Note Samba", "style": "Melodic fragment", "fragments": ["B3", "A2", "A5", "A2"], "description": "Melodic fragment from One Note Samba."},
    {"id": "frag-melodico-04-jura", "name": "Frag. Melódico 4 — Jura", "style": "Melodic fragment", "fragments": ["A3", "B5", "A3", "B5"], "description": "Melodic fragment from Jura. Same sequence as Baião 2, kept as separate stylistic label."},
    {"id": "frag-melodico-05-noites-cariocas", "name": "Frag. Melódico 5 — Noites Cariocas", "style": "Melodic fragment", "fragments": ["A2", "B2", "A2", "B2"], "description": "Melodic fragment from Noites Cariocas."}
  ];
